sonar.projectKey=danielso2007_fc-ci-node-github-actions
sonar.organization=danielso2007
sonar.projectName=GitHub Action Node
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/*.test.js

sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
