sonar.projectKey=danielso2007_fc-ci-node-github-actions
sonar.organization=danielso2007
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
